#define IDI_GLO_APP 101
#pragma once
#define IDI_GLO_SETTINGS_LIGHT 201
#define IDI_GLO_SETTINGS_DARK  202
#define IDI_GLO_SUN_LIGHT      203
#define IDI_GLO_SUN_DARK       204
#define IDI_GLO_MOON_LIGHT     205
#define IDI_GLO_MOON_DARK      206
#define IDI_GLO_BACK_LIGHT      207
#define IDI_GLO_BACK_DARK       208
#define IDI_GLO_OFFICIAL_LIGHT  209
#define IDI_GLO_OFFICIAL_DARK   210
#define IDI_GLO_GITHUB_LIGHT    211
#define IDI_GLO_GITHUB_DARK     212
#define IDI_GLO_FACEBOOK_LIGHT  213
#define IDI_GLO_FACEBOOK_DARK   214

#define IDI_GLO_PASTE_LIGHT      215
#define IDI_GLO_PASTE_DARK       216
#define IDI_GLO_IMPORT_LIGHT     217
#define IDI_GLO_IMPORT_DARK      218
#define IDI_GLO_CONNECT_LIGHT    219
#define IDI_GLO_CONNECT_DARK     220
#define IDI_GLO_DISCONNECT_LIGHT 221
#define IDI_GLO_DISCONNECT_DARK  222
