#!/usr/bin/env python3
"""Build the per-user GLO NSIS installer entirely from local inputs."""
import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]


def default_bin_root():
    """Return the repository-local artifact root.

    Public OSS builds never inspect parent-directory layouts. Callers that need
    another destination must pass --build-dir/--output-dir explicitly.
    """
    return ROOT / "bin"


def find_makensis(explicit: str | None):
    if explicit:
        p = Path(explicit).expanduser().resolve()
        if p.is_file():
            return p
        raise FileNotFoundError(f"makensis not found: {p}")
    found = shutil.which("makensis") or shutil.which("makensis.exe")
    if found:
        return Path(found).resolve()
    for env_name in ("ProgramFiles(x86)", "ProgramFiles"):
        base = os.environ.get(env_name)
        if base:
            p = Path(base) / "NSIS" / "makensis.exe"
            if p.is_file():
                return p
    raise FileNotFoundError("makensis was not found. Install NSIS locally or pass --makensis. No dependency was downloaded.")


def clean_installer_outputs(out: Path) -> None:
    """Remove stale GLO installer artifacts without deleting unrelated custom-output files."""
    if not out.exists():
        return
    for pattern in ("GLO-Setup-*.exe", "GLO-Setup-*.exe.sha256"):
        for path in out.glob(pattern):
            if path.is_file() or path.is_symlink():
                path.unlink()



def nsis_quote(value: str) -> str:
    """Quote a value for an NSIS source file, not for the process command line."""
    if any(ch in value for ch in ("\0", "\r", "\n")):
        raise ValueError("NSIS define values must be single-line strings")
    # NSIS uses '$' as its escape prefix. Escape literal dollars first, then
    # embedded quotes. Windows paths do not require backslash escaping.
    return '"' + value.replace('$', '$$').replace('"', '$\\"') + '"'


def read_branding() -> dict:
    branding_path = ROOT / "installer" / "BRANDING.json"
    data = json.loads(branding_path.read_text(encoding="utf-8"))
    if data.get("schema") != 1:
        raise ValueError("installer/BRANDING.json schema must be 1")

    def validate_url(name: str, *, host: str | None = None) -> str:
        value = str(data.get(name, "")).strip()
        if not value:
            return ""
        parsed = urlparse(value)
        if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
            raise ValueError(f"{name} must be an https URL without embedded credentials")
        hostname = parsed.hostname.lower()
        if host and hostname not in {host, f"www.{host}"}:
            raise ValueError(f"{name} must point to {host}")
        if host == "github.com" and len([part for part in parsed.path.split("/") if part]) < 2:
            raise ValueError("github_url must point to an exact GitHub owner/repository URL")
        if host == "facebook.com" and not [part for part in parsed.path.split("/") if part]:
            raise ValueError("facebook_url must point to an exact Facebook page/profile URL")
        return value

    official = validate_url("official_url")
    if not official:
        raise ValueError("official_url must be configured")
    return {
        "official_url": official,
        "github_url": validate_url("github_url", host="github.com"),
        "facebook_url": validate_url("facebook_url", host="facebook.com"),
    }


def write_nsis_driver(
    path: Path, *, release: str, version: str, display_version: str, branding: dict,
    installer_name: str
) -> None:
    """Generate a relocatable NSIS driver.

    All filesystem references consumed by makensis are relative to the driver
    working directory. This avoids coupling release builds to GitHub runner
    drive letters, MSYS path translation, checkout locations, or a developer's
    machine layout.
    """
    values = {
        "STAGE_DIR": "stage",
        "OUT_FILE": f"output/{installer_name}",
        "RELEASE_VERSION": release,
        "PROTOCOL_VERSION": version,
        "DISPLAY_VERSION": display_version,
        "OFFICIAL_URL": branding["official_url"],
        "GITHUB_URL": branding["github_url"],
        "FACEBOOK_URL": branding["facebook_url"],
        "HAS_GITHUB": "1" if branding["github_url"] else "0",
        "HAS_FACEBOOK": "1" if branding["facebook_url"] else "0",
        "INSTALLER_ICON": "glo-installer.ico",
    }
    lines = [
        "; Generated by tools/build_installer.py. Do not edit.",
        "; All build paths are relative to this staging directory.",
    ]
    for name, value in values.items():
        lines.append(f"!define {name} {nsis_quote(value)}")
    lines.append('!include "GLO.nsi"')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8-sig", newline="\n")

def hash_tree(root: Path) -> str:
    h=hashlib.sha256()
    for path in sorted(p for p in root.rglob("*") if p.is_file()):
        rel=path.relative_to(root).as_posix().encode(); h.update(len(rel).to_bytes(4,"big")); h.update(rel)
        with path.open("rb") as f:
            for chunk in iter(lambda:f.read(1024*1024),b""): h.update(chunk)
    return h.hexdigest()

def installer_cache_root() -> Path:
    root=Path(os.environ.get("GLO_BUILD_CACHE_DIR") or (Path(tempfile.gettempdir()) / "glo-build-cache")) / "installer"
    root.mkdir(parents=True,exist_ok=True);
    try: root.parent.chmod(0o700); root.chmod(0o700)
    except OSError: pass
    return root

def main():
    started=time.monotonic()
    ap = argparse.ArgumentParser()
    bin_root = default_bin_root()
    ap.add_argument("--build-dir", type=Path, default=bin_root / "app", help="bin/app or CMake output directory")
    ap.add_argument("--output-dir", type=Path, default=bin_root / "installer")
    ap.add_argument("--makensis")
    args = ap.parse_args()
    version = (ROOT / "VERSION").read_text(encoding='utf-8').strip()
    release = (ROOT / "RELEASE").read_text(encoding='utf-8').strip()
    display_version = (ROOT / "DISPLAY_VERSION").read_text(encoding='utf-8').strip()
    if not version or not release:
        raise ValueError("VERSION and RELEASE must not be empty")
    release_pattern=rf"{re.escape(version)}(?:-(?:r[1-9][0-9]*|alpha(?:\.[1-9][0-9]*)?|beta(?:\.[1-9][0-9]*)?))?"
    if not re.fullmatch(release_pattern, release):
        raise ValueError("RELEASE must be VERSION, VERSION-rN, VERSION-alpha[.N], or VERSION-beta[.N]")
    if display_version != release and not re.fullmatch(rf"{re.escape(version)}-[0-9]{{8}}", display_version):
        raise ValueError("DISPLAY_VERSION must equal RELEASE (legacy VERSION-MMDDYYYY is also accepted)")
    branding = read_branding()
    icon = ROOT / "installer" / "resources" / "glo-installer.ico"
    if not icon.is_file():
        raise FileNotFoundError(f"installer icon is missing: {icon}")
    build_dir = args.build_dir.resolve()
    out = args.output_dir.resolve()

    # Every installer build starts from a clean staging tree and removes stale
    # GLO installer outputs. This prevents an old successful EXE from being
    # mistaken for the result of a failed/new build.
    installer_build_root = ROOT / "build" / "installer"
    if installer_build_root.exists():
        shutil.rmtree(installer_build_root)
    clean_installer_outputs(out)
    stage = installer_build_root / "stage"
    stage.mkdir(parents=True)

    subprocess.run([sys.executable, str(ROOT / "tools" / "package_windows.py"), str(build_dir), str(stage)], check=True)
    makensis = find_makensis(args.makensis)
    out.mkdir(parents=True, exist_ok=True)
    name = f"GLO-Setup-{release}-x64.exe"; installer = out / name
    script = ROOT / "installer" / "nsis" / "GLO.nsi"
    cache_seed = "|".join([hash_tree(stage),hashlib.sha256(script.read_bytes()).hexdigest(),hashlib.sha256(icon.read_bytes()).hexdigest(),hashlib.sha256((ROOT/"installer"/"BRANDING.json").read_bytes()).hexdigest(),version,release,display_version,hashlib.sha256(makensis.read_bytes()).hexdigest()])
    cache_key=hashlib.sha256(cache_seed.encode()).hexdigest(); cache_dir=installer_cache_root()/cache_key; cached=cache_dir/name; cache_hit=cached.is_file() and cached.stat().st_size>=64
    if cache_hit:
        shutil.copy2(cached,installer); data=installer.read_bytes()
        if data[:2] != b"MZ": cache_hit=False
    if not cache_hit:
        # makensis receives only a driver filename and resolves every input from
        # this isolated working directory. No checkout-absolute path is embedded
        # in the generated NSIS source.
        driver = installer_build_root / "GLO.generated.nsi"
        local_script = installer_build_root / "GLO.nsi"
        local_icon = installer_build_root / "glo-installer.ico"
        local_output = installer_build_root / "output"
        local_output.mkdir(parents=True, exist_ok=True)
        shutil.copy2(script, local_script)
        shutil.copy2(icon, local_icon)
        write_nsis_driver(
            driver, release=release, version=version, display_version=display_version,
            branding=branding, installer_name=name
        )
        subprocess.run([str(makensis), driver.name], check=True, cwd=installer_build_root)
        built_installer = local_output / name
        if not built_installer.is_file():
            raise RuntimeError(f"NSIS did not produce the expected installer: {built_installer}")
        data = built_installer.read_bytes()
        if len(data) < 64 or data[:2] != b"MZ":
            raise RuntimeError("NSIS did not produce a valid Windows executable")
        shutil.copy2(built_installer, installer)
        cache_dir.mkdir(parents=True,exist_ok=True); shutil.copy2(installer,cached)
    digest = hashlib.sha256(data).hexdigest(); (out / f"{name}.sha256").write_text(f"{digest}  {name}\n", encoding="utf-8", newline="\n")
    print(installer); print("sha256", digest); print("installer cache", "HIT" if cache_hit else "MISS"); print("installer elapsed", f"{time.monotonic()-started:.2f}s")


if __name__ == "__main__":
    main()
